import { sql } from "./data/lakebase";

// Append-only audit trail for platform changes: who edited a report, who
// changed an access policy, who renamed a saved view. Distinct from usage
// telemetry, which records viewing rather than mutation.
//
// Ids are generated by the database rather than by a read-then-increment. The
// previous sequence approach needed a process-wide mutex to stay correct,
// which silently produces duplicate ids once the app runs on more than one
// replica.

export interface LogEntry {
	recordType: string;
	recordId: string;
	action: string;
	fieldName?: string | null;
	oldValue?: string | null;
	newValue?: string | null;
	changedBy: string;
	notes?: string | null;
}

// Writes every entry in a single insert. Failures are swallowed: an unwritable
// audit row must not fail the change it describes.
export async function insertLogs(entries: LogEntry[]): Promise<void> {
	if (entries.length === 0) return;

	const columns = [
		"record_type", "record_id", "action", "field_name",
		"old_value", "new_value", "changed_by", "notes",
	];

	try {
		const params: unknown[] = [];
		const tuples = entries.map((entry, i) => {
			const base = i * columns.length;
			params.push(
				entry.recordType,
				entry.recordId,
				entry.action,
				entry.fieldName ?? null,
				entry.oldValue ?? null,
				entry.newValue ?? null,
				entry.changedBy,
				entry.notes ?? null,
			);
			const markers = columns.map((_, c) => `$${base + c + 1}`);
			return `(${markers.join(",")})`;
		});

		await sql(
			`INSERT INTO activity_log (${columns.join(",")}) VALUES ${tuples.join(",")}`,
			params,
		);
	} catch (error) {
		console.warn(
			`Activity log insert failed (${entries.length} entries):`,
			error,
		);
	}
}

export async function insertLog(entry: LogEntry): Promise<void> {
	await insertLogs([entry]);
}
