import { sql, transaction } from "../data/lakebase";
import type { PolicyClass } from "../auth/policy";
import { insertLog } from "../activityLog";
import { invalidateDefinitions } from "./definitionCache";
import {
	effective,
	refuse,
	refuseAddPage,
	unprotected,
	type PageProtection,
	type ReportProtection,
} from "./pageProtection";
import { record } from "../telemetry/usage";
import { getExplicitContext, resolveReportAccess } from "./access";
import { getSource } from "../semantic/registry";
import {
	describeProblems,
	hasError,
	validateVisual,
} from "../visuals/validate";

// Editing a report.
//
// A report has one definition. When a central editor adds a visual it is added
// for everyone, because there is no per-user copy to diverge from. Personal
// customization lives in saved views, which are deltas against this definition
// and therefore absorb an edit rather than being replaced by it. See
// lib/platform/overlay.ts.
//
// Two things keep concurrent editing honest:
//
//   Optimistic concurrency. Every write carries the version it was based on.
//   A stale version is rejected rather than merged, so the second of two
//   simultaneous editors is told to reload instead of silently overwriting.
//
//   An op log. Each accepted change appends to report_ops with a monotonic
//   sequence, which is what other sessions replay to catch up. NOTIFY is only
//   a latency hint on top of it.

export class EditConflictError extends Error {
	constructor(
		message: string,
		readonly currentVersion: number,
	) {
		super(message);
	}
}

export class EditForbiddenError extends Error {}

// A definition the catalogue says cannot be drawn.
export class EditRejectedError extends Error {}

// Position on the canvas. Stored in its own columns rather than inside the
// config blob, so a layout query does not have to parse JSON and so the two
// cannot disagree about where a visual sits.
export interface VisualLayout {
	x: number;
	y: number;
	w: number;
	h: number;
}

export type EditOperation =
	| {
			type: "addVisual";
			// Generated by the client so every session applies the op to the
			// same id. Letting the database mint it would mean a remote
			// session could not reproduce the insert, and the two copies would
			// diverge the moment anyone edited the new visual.
			visualId?: string;
			pageId: string;
			visualType: string;
			title?: string | null;
			sourceKey: string | null;
			config?: Record<string, unknown>;
			layout?: VisualLayout;
	  }
	| {
			type: "updateVisual";
			visualId: string;
			title?: string | null;
			visualType?: string;
			sourceKey?: string | null;
			config?: Record<string, unknown>;
			layout?: VisualLayout;
	  }
	| { type: "removeVisual"; visualId: string }
	| { type: "reorderVisuals"; pageId: string; visualIds: string[] }
	| {
			type: "updateReport";
			title?: string;
			description?: string | null;
	  }
	| {
			type: "updatePage";
			pageId: string;
			title?: string;
			// Merged into the page's existing settings rather than replacing
			// them, so setting one does not clear another.
			config?: Record<string, unknown>;
	  }
	| {
			type: "addPage";
			// Client-generated for the same reason a visual's is: every session
			// has to apply the insert to the same id.
			pageId: string;
			title: string;
			slug: string;
			sourceKey?: string | null;
	  }
	| { type: "removePage"; pageId: string }
	| { type: "reorderPages"; pageIds: string[] };

export interface EditRequest {
	reportId: string;
	// Version the editor's copy was based on.
	baseVersion: number;
	operations: EditOperation[];
	// Identifies the editing session, so a client can ignore echoes of its own
	// operations when they arrive back over the change feed.
	originId?: string;
}

export interface EditResult {
	version: number;
	// Sequence of the last op written, so a client knows where it is caught up
	// to without re-reading the feed.
	seq: number;
}

// Returns whether the report is a personal page, which the caller needs anyway
// and which is already loaded here.
export async function assertCanEdit(
	policy: PolicyClass,
	email: string,
	reportId: string,
): Promise<boolean> {
	const rows = await sql<{
		category_id: string | null;
		is_personal: boolean;
		owner_email: string | null;
	}>(
		`SELECT category_id, is_personal, owner_email
		 FROM reports WHERE report_id = $1 AND is_active = TRUE`,
		[reportId],
	);
	const report = rows[0];
	if (!report) throw new EditForbiddenError("Report not found");

	const context = await getExplicitContext(policy, email);
	const access = resolveReportAccess(
		context.grants,
		{
			reportId,
			categoryId: report.category_id,
			isPersonal: report.is_personal,
			ownerEmail: report.owner_email,
		},
		context.email,
		"edit",
		context.baseline,
	);
	if (!access.allowed) {
		throw new EditForbiddenError(
			"You do not have permission to edit this report",
		);
	}

	return report.is_personal;
}

// Checks every visual an edit would store against the catalogue.
//
// Before this, applyEdits took whatever arrived: a visual_type nothing renders,
// a chart with no measure, a setting of the wrong kind. It was safe only
// because the editor UI was the only thing that could produce an edit, and that
// stopped being true the moment a second authoring surface existed.
//
// Runs before the transaction opens. A refusal should not have taken a row lock
// on the report first, and the reads here are of the semantic registry, which
// is already in memory.
// Refuses operations against a page an administrator has locked.
//
// Enforced here rather than in the editor, because a lock the editor honours
// and the write path does not is a lock anybody can lift by sending the
// operation themselves. This runs before the transaction opens, so a refused
// batch changes nothing at all rather than being half applied.
//
// A page an operation names by visual has to be looked up: removing a visual
// says which visual, not which page it is on, and that is exactly the operation
// a lock is there to stop.
async function assertPagesAreUnlocked(
	reportId: string,
	operations: EditOperation[],
): Promise<void> {
	const named = new Set<string>();
	const byVisual: string[] = [];
	let addsAPage = false;

	for (const op of operations) {
		// A page being created cannot already be locked, but the report it is
		// being added to can refuse it.
		if (op.type === "addPage") {
			addsAPage = true;
			continue;
		}
		if ("pageId" in op && typeof op.pageId === "string") {
			named.add(op.pageId);
			continue;
		}
		if (op.type === "updateVisual" || op.type === "removeVisual") {
			byVisual.push(op.visualId);
		}
	}

	const pageOfVisual = new Map<string, string>();
	if (byVisual.length > 0) {
		const rows = await sql<{ visual_id: string; page_id: string }>(
			`SELECT visual_id::text AS visual_id, page_id::text AS page_id
			 FROM report_visuals WHERE visual_id = ANY($1::uuid[])`,
			[byVisual],
		);
		for (const row of rows) {
			pageOfVisual.set(row.visual_id, row.page_id);
			named.add(row.page_id);
		}
	}

	if (named.size === 0 && !addsAPage) return;

	// A report can be locked as a whole. Combined with each page's own pair
	// rather than overriding it, so locking a report cannot quietly lift a
	// lock somebody put on one page of it.
	const reportRows = await sql<{
		protect_delete: boolean;
		protect_edit: boolean;
		protect_add_page: boolean;
	}>(
		`SELECT protect_delete, protect_edit, protect_add_page
		   FROM reports WHERE report_id = $1`,
		[reportId],
	);
	const reportLocks: ReportProtection = {
		protectDelete: reportRows[0]?.protect_delete === true,
		protectEdit: reportRows[0]?.protect_edit === true,
		protectAddPage: reportRows[0]?.protect_add_page === true,
	};

	if (addsAPage) {
		const said = refuseAddPage("addPage", reportLocks);
		if (said) throw new EditRejectedError(said.reason);
	}

	if (named.size === 0) return;

	const rows = await sql<{
		page_id: string;
		protect_delete: boolean;
		protect_edit: boolean;
	}>(
		`SELECT page_id::text AS page_id, protect_delete, protect_edit
		 FROM report_pages WHERE page_id = ANY($1::uuid[])`,
		[Array.from(named)],
	);

	const locks = new Map<string, PageProtection>(
		rows.map((row) => [
			row.page_id,
			{
				protectDelete: row.protect_delete,
				protectEdit: row.protect_edit,
			},
		]),
	);

	for (const op of operations) {
		if (op.type === "addPage") continue;
		const pageId =
			"pageId" in op && typeof op.pageId === "string"
				? op.pageId
				: op.type === "updateVisual" || op.type === "removeVisual"
					? pageOfVisual.get(op.visualId)
					: undefined;
		if (!pageId) continue;

		const said = refuse(
			op.type,
			effective(reportLocks, locks.get(pageId) ?? unprotected),
		);
		if (said) throw new EditRejectedError(said.reason);
	}
}

async function assertDefinitionsAreDrawable(
	operations: EditOperation[],
): Promise<void> {
	// An update may change only a title, in which case the type and the source
	// it is checked against are the stored ones rather than the op's.
	const needStored = operations
		.filter(
			(op): op is Extract<EditOperation, { type: "updateVisual" }> =>
				op.type === "updateVisual" && op.config !== undefined,
		)
		.map((op) => op.visualId);

	const stored = new Map<
		string,
		{ type: string; sourceKey: string | null }
	>();
	if (needStored.length > 0) {
		const rows = await sql<{
			visual_id: string;
			visual_type: string;
			source_key: string | null;
		}>(
			`SELECT visual_id::text AS visual_id, visual_type, source_key
			 FROM report_visuals WHERE visual_id = ANY($1::uuid[])`,
			[needStored],
		);
		for (const row of rows) {
			stored.set(row.visual_id, {
				type: row.visual_type,
				sourceKey: row.source_key,
			});
		}
	}

	for (const op of operations) {
		if (op.type !== "addVisual" && op.type !== "updateVisual") continue;
		if (op.type === "updateVisual" && op.config === undefined) continue;

		const previous =
			op.type === "updateVisual" ? stored.get(op.visualId) : undefined;
		const visualType = op.visualType ?? previous?.type;
		if (!visualType) continue;

		const sourceKey =
			op.sourceKey !== undefined
				? op.sourceKey
				: (previous?.sourceKey ?? null);
		const source = sourceKey ? getSource(sourceKey) : null;

		// A source key naming nothing the registry knows is refused outright.
		// The query would fail later anyway, with a message about a table
		// instead of about the visual.
		if (sourceKey && !source) {
			throw new EditRejectedError(
				`There is no source called ${sourceKey}.`,
			);
		}

		const problems = validateVisual(
			visualType,
			(op.config ?? {}) as Record<string, unknown>,
			source
				? {
						dimensions: source.dimensions.map((f) => f.name),
						measures: source.measures.map((f) => f.name),
					}
				: null,
		);

		if (hasError(problems)) {
			throw new EditRejectedError(describeProblems(problems));
		}

		// Drift rather than a mistake: a field the semantic layer dropped since
		// the report was authored. Allowed through, because refusing would
		// block an unrelated edit until somebody else fixed the source, and
		// logged, because otherwise it is invisible until a reader asks why a
		// column is missing.
		for (const problem of problems) {
			console.warn(
				`Visual definition drift on ${visualType}: ${problem.message}`,
			);
		}
	}
}

export async function applyEdits(
	policy: PolicyClass,
	email: string,
	request: EditRequest,
): Promise<EditResult> {
	const personal = await assertCanEdit(policy, email, request.reportId);

	if (request.operations.length === 0) {
		throw new Error("No operations supplied");
	}

	await assertDefinitionsAreDrawable(request.operations);
	await assertPagesAreUnlocked(request.reportId, request.operations);

	return transaction(async (client) => {
		// Locking the report row serializes concurrent edits to it. Without
		// this, two editors could both read version 4, both write version 5,
		// and one change would vanish.
		const current = await client.query<{ version: string }>(
			`SELECT version FROM reports WHERE report_id = $1 FOR UPDATE`,
			[request.reportId],
		);
		const currentVersion = Number(current.rows[0]?.version ?? 0);

		if (currentVersion !== request.baseVersion) {
			throw new EditConflictError(
				"This report changed while you were editing it. Reload to see the current version.",
				currentVersion,
			);
		}

		// The client sends layout inside config because that is one object to
		// carry through the editor. It is split out here so the columns stay
		// the single source of position.
		const splitLayout = (
			config: Record<string, unknown> | undefined,
			explicit: VisualLayout | undefined,
		): { config: Record<string, unknown>; layout: VisualLayout | null } => {
			if (!config) return { config: {}, layout: explicit ?? null };
			const { layout, ...rest } = config as Record<string, unknown> & {
				layout?: VisualLayout;
			};
			return { config: rest, layout: explicit ?? layout ?? null };
		};

		for (const op of request.operations) {
			switch (op.type) {
				case "addVisual": {
					const next = await client.query<{ sort_order: number }>(
						`SELECT COALESCE(MAX(sort_order), -1) + 1 AS sort_order
						 FROM report_visuals WHERE page_id = $1`,
						[op.pageId],
					);
					const { config, layout } = splitLayout(
						op.config,
						op.layout,
					);
					await client.query(
						`INSERT INTO report_visuals
						   (visual_id, page_id, visual_type, title, source_key, config,
						    layout_x, layout_y, layout_w, layout_h, sort_order)
						 VALUES (COALESCE($11::uuid, gen_random_uuid()),
						         $1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
						 ON CONFLICT (visual_id) DO NOTHING`,
						[
							op.pageId,
							op.visualType,
							op.title ?? null,
							op.sourceKey,
							JSON.stringify(config),
							layout?.x ?? 0,
							layout?.y ?? 0,
							layout?.w ?? 6,
							layout?.h ?? 4,
							next.rows[0]?.sort_order ?? 0,
							op.visualId ?? null,
						],
					);
					break;
				}

				case "updateVisual": {
					// Only the supplied fields change, so a client editing one
					// property does not have to send the whole visual back and
					// risk clobbering a property it never showed.
					const { config, layout } = splitLayout(
						op.config,
						op.layout,
					);
					await client.query(
						`UPDATE report_visuals SET
						   title = COALESCE($2, title),
						   visual_type = COALESCE($3, visual_type),
						   source_key = COALESCE($4, source_key),
						   config = COALESCE($5::jsonb, config),
						   layout_x = COALESCE($6, layout_x),
						   layout_y = COALESCE($7, layout_y),
						   layout_w = COALESCE($8, layout_w),
						   layout_h = COALESCE($9, layout_h)
						 WHERE visual_id = $1`,
						[
							op.visualId,
							op.title ?? null,
							op.visualType ?? null,
							op.sourceKey ?? null,
							op.config ? JSON.stringify(config) : null,
							layout?.x ?? null,
							layout?.y ?? null,
							layout?.w ?? null,
							layout?.h ?? null,
						],
					);
					break;
				}

				case "removeVisual":
					// Deactivated rather than deleted, so a version restore can
					// bring it back and the audit trail still resolves it.
					await client.query(
						`UPDATE report_visuals SET is_active = FALSE WHERE visual_id = $1`,
						[op.visualId],
					);
					break;

				case "reorderVisuals":
					for (let i = 0; i < op.visualIds.length; i++) {
						await client.query(
							`UPDATE report_visuals SET sort_order = $2
							 WHERE visual_id = $1 AND page_id = $3`,
							[op.visualIds[i], i, op.pageId],
						);
					}
					break;

				case "updateReport":
					await client.query(
						`UPDATE reports SET
						   title = COALESCE($2, title),
						   description = COALESCE($3, description)
						 WHERE report_id = $1`,
						[
							request.reportId,
							op.title ?? null,
							op.description ?? null,
						],
					);
					break;

				case "addPage": {
					const next = await client.query<{ sort_order: number }>(
						`SELECT COALESCE(MAX(sort_order), -1) + 1 AS sort_order
						 FROM report_pages WHERE report_id = $1`,
						[request.reportId],
					);
					await client.query(
						`INSERT INTO report_pages
						   (page_id, report_id, slug, title, source_key, sort_order)
						 VALUES ($1,$2,$3,$4,$5,$6)
						 ON CONFLICT (page_id) DO NOTHING`,
						[
							op.pageId,
							request.reportId,
							op.slug,
							op.title,
							op.sourceKey ?? null,
							next.rows[0]?.sort_order ?? 0,
						],
					);
					break;
				}

				case "reorderPages":
					// Operations are cast from the request body rather than
					// parsed, so the shape is checked here before it is walked.
					if (!Array.isArray(op.pageIds)) break;
					for (let i = 0; i < op.pageIds.length; i++) {
						await client.query(
							`UPDATE report_pages SET sort_order = $2
							 WHERE page_id = $1 AND report_id = $3`,
							[op.pageIds[i], i, request.reportId],
						);
					}
					break;

				case "removePage":
					// Deactivated rather than deleted, so a restore brings it
					// back and the visuals on it are not lost with it.
					await client.query(
						`UPDATE report_pages SET is_active = FALSE
						 WHERE page_id = $2 AND report_id = $1`,
						[request.reportId, op.pageId],
					);
					break;

				case "updatePage":
					await client.query(
						`UPDATE report_pages SET
						   title = COALESCE($3, title),
						   config = config || COALESCE($4::jsonb, '{}'::jsonb)
						 WHERE page_id = $2 AND report_id = $1`,
						[
							request.reportId,
							op.pageId,
							op.title ?? null,
							op.config ? JSON.stringify(op.config) : null,
						],
					);
					break;
			}
		}

		const nextVersion = currentVersion + 1;
		await client.query(
			`UPDATE reports
			 SET version = $2, modified_by = $3, modified_on = now()
			 WHERE report_id = $1`,
			[request.reportId, nextVersion, email],
		);

		// This replica drops what it was holding immediately, so an editor
		// never watches their own change wait out a cache. Another replica
		// serves the previous definition until its entry lapses, which is the
		// price of not asking the database whether it is still current.
		invalidateDefinitions(`report-body:${request.reportId}`);
		invalidateDefinitions("report:");

		// The op log is what other sessions replay. It is written inside the
		// same transaction as the change itself, so a session can never see an
		// op describing a change that did not land.
		const opRow = await client.query<{ seq: string }>(
			`INSERT INTO report_ops (report_id, actor, origin_id, op)
			 VALUES ($1, $2, $3, $4)
			 RETURNING seq`,
			[
				request.reportId,
				email,
				request.originId ?? null,
				JSON.stringify({
					version: nextVersion,
					operations: request.operations,
				}),
			],
		);
		const seq = Number(opRow.rows[0]?.seq ?? 0);

		// A snapshot per version, so any version can be restored and an edit
		// history reconstructed.
		//
		// Everything a restore has to put back, which means the layout columns
		// as well: without them a restore returned the right visuals with every
		// position lost, which is worse than not offering one.
		//
		// Not for a personal page. A curated report is edited by several people
		// and read by many, so the record of who changed what earns three
		// queries and a full copy on every save. A page somebody is building
		// for themselves is saved constantly by one person, and the history
		// would be a copy of the whole page per keystroke-sized change, kept
		// for a restore nobody asks for.
		if (personal) {
			return { version: nextVersion, seq };
		}

		const snapshot = await client.query(
			`SELECT v.visual_id, v.page_id, v.visual_type, v.title, v.source_key,
			        v.config, v.layout_x, v.layout_y, v.layout_w, v.layout_h,
			        v.sort_order, v.is_active
			 FROM report_visuals v
			 JOIN report_pages p ON p.page_id = v.page_id
			 WHERE p.report_id = $1`,
			[request.reportId],
		);
		const pageSnapshot = await client.query(
			`SELECT page_id, slug, title, source_key, config, sort_order, is_active
			 FROM report_pages WHERE report_id = $1`,
			[request.reportId],
		);
		const reportSnapshot = await client.query(
			`SELECT title, description FROM reports WHERE report_id = $1`,
			[request.reportId],
		);

		await client.query(
			`INSERT INTO report_versions (report_id, version, snapshot, created_by)
			 VALUES ($1, $2, $3, $4)
			 ON CONFLICT (report_id, version) DO NOTHING`,
			[
				request.reportId,
				nextVersion,
				JSON.stringify({
					visuals: snapshot.rows,
					pages: pageSnapshot.rows,
					report: reportSnapshot.rows[0] ?? null,
				}),
				email,
			],
		);

		// Notification is a hint. Delivery is guaranteed by the sequence above,
		// so a listener that missed this still catches up on its next poll.
		await client.query(`SELECT pg_notify($1, $2)`, [
			`report_${request.reportId.replace(/-/g, "")}`,
			JSON.stringify({ seq, version: nextVersion, actor: email }),
		]);

		// Audit and telemetry go outside the transaction's critical path but
		// still describe what was committed.
		void insertLog({
			recordType: "report",
			recordId: request.reportId,
			action: "edit",
			changedBy: email,
			newValue: JSON.stringify({
				version: nextVersion,
				operations: request.operations.map((o) => o.type),
			}),
		});
		record({
			occurredOn: new Date().toISOString(),
			userEmail: email,
			policyClass: policy.id,
			eventType: "edit",
			reportId: request.reportId,
		});

		return { version: nextVersion, seq };
	});
}

export interface ReportOp {
	seq: number;
	actor: string;
	originId: string | null;
	op: { version: number; operations: EditOperation[] };
	createdOn: string;
}

// Everything that happened to a report after a given sequence. This is how a
// session catches up, whether it was notified or simply polled.
export async function opsSince(
	reportId: string,
	afterSeq: number,
	limit = 200,
): Promise<ReportOp[]> {
	const rows = await sql<{
		seq: string;
		actor: string;
		origin_id: string | null;
		op: ReportOp["op"];
		created_on: string;
	}>(
		`SELECT seq, actor, origin_id, op, created_on
		 FROM report_ops
		 WHERE report_id = $1 AND seq > $2
		 ORDER BY seq
		 LIMIT $3`,
		[reportId, afterSeq, limit],
	);

	return rows.map((row) => ({
		seq: Number(row.seq),
		actor: row.actor,
		originId: row.origin_id,
		op: row.op,
		createdOn: row.created_on,
	}));
}

// Trims the op log. Versions keep the full history, so ops only need to cover
// the window a disconnected session might have missed.
export async function pruneOps(olderThanHours = 48): Promise<number> {
	const rows = await sql<{ count: string }>(
		`WITH deleted AS (
		   DELETE FROM report_ops
		   WHERE created_on < now() - ($1 || ' hours')::interval
		   RETURNING 1
		 )
		 SELECT count(*)::text AS count FROM deleted`,
		[String(olderThanHours)],
	);
	return Number(rows[0]?.count ?? 0);
}
