import { sql, transaction } from "../data/lakebase";
import type { PolicyClass } from "../auth/policy";
import { insertLog } from "../activityLog";
import { record } from "../telemetry/usage";
import {
	baselinePermission,
	getGrants,
	resolveReportAccess,
} from "./access";

// Editing a report.
//
// A report has one definition. When a central editor adds a visual it is added
// for everyone, because there is no per-user copy to diverge from. Personal
// customization lives in saved views, which are deltas against this definition
// and therefore absorb an edit rather than being replaced by it. See
// lib/platform/overlay.ts.
//
// Two things keep concurrent editing honest:
//
//   Optimistic concurrency. Every write carries the version it was based on.
//   A stale version is rejected rather than merged, so the second of two
//   simultaneous editors is told to reload instead of silently overwriting.
//
//   An op log. Each accepted change appends to report_ops with a monotonic
//   sequence, which is what other sessions replay to catch up. NOTIFY is only
//   a latency hint on top of it.

export class EditConflictError extends Error {
	constructor(
		message: string,
		readonly currentVersion: number,
	) {
		super(message);
	}
}

export class EditForbiddenError extends Error {}

// Position on the canvas. Stored in its own columns rather than inside the
// config blob, so a layout query does not have to parse JSON and so the two
// cannot disagree about where a visual sits.
export interface VisualLayout {
	x: number;
	y: number;
	w: number;
	h: number;
}

export type EditOperation =
	| {
			type: "addVisual";
			// Generated by the client so every session applies the op to the
			// same id. Letting the database mint it would mean a remote
			// session could not reproduce the insert, and the two copies would
			// diverge the moment anyone edited the new visual.
			visualId?: string;
			pageId: string;
			visualType: string;
			title?: string | null;
			sourceKey: string | null;
			config?: Record<string, unknown>;
			layout?: VisualLayout;
	  }
	| {
			type: "updateVisual";
			visualId: string;
			title?: string | null;
			visualType?: string;
			sourceKey?: string | null;
			config?: Record<string, unknown>;
			layout?: VisualLayout;
	  }
	| { type: "removeVisual"; visualId: string }
	| { type: "reorderVisuals"; pageId: string; visualIds: string[] }
	| {
			type: "updateReport";
			title?: string;
			description?: string | null;
	  }
	| {
			type: "updatePage";
			pageId: string;
			title?: string;
			// Merged into the page's existing settings rather than replacing
			// them, so setting one does not clear another.
			config?: Record<string, unknown>;
	  }
	| {
			type: "addPage";
			// Client-generated for the same reason a visual's is: every session
			// has to apply the insert to the same id.
			pageId: string;
			title: string;
			slug: string;
			sourceKey?: string | null;
	  }
	| { type: "removePage"; pageId: string };

export interface EditRequest {
	reportId: string;
	// Version the editor's copy was based on.
	baseVersion: number;
	operations: EditOperation[];
	// Identifies the editing session, so a client can ignore echoes of its own
	// operations when they arrive back over the change feed.
	originId?: string;
}

export interface EditResult {
	version: number;
	// Sequence of the last op written, so a client knows where it is caught up
	// to without re-reading the feed.
	seq: number;
}

export async function assertCanEdit(
	policy: PolicyClass,
	email: string,
	reportId: string,
): Promise<void> {
	const rows = await sql<{ category_id: string | null }>(
		`SELECT category_id FROM reports WHERE report_id = $1 AND is_active = TRUE`,
		[reportId],
	);
	const report = rows[0];
	if (!report) throw new EditForbiddenError("Report not found");

	const grants = await getGrants(policy, email);
	const access = resolveReportAccess(
		grants,
		reportId,
		report.category_id,
		"edit",
		baselinePermission(policy),
	);
	if (!access.allowed) {
		throw new EditForbiddenError(
			"You do not have permission to edit this report",
		);
	}
}

export async function applyEdits(
	policy: PolicyClass,
	email: string,
	request: EditRequest,
): Promise<EditResult> {
	await assertCanEdit(policy, email, request.reportId);

	if (request.operations.length === 0) {
		throw new Error("No operations supplied");
	}

	return transaction(async (client) => {
		// Locking the report row serializes concurrent edits to it. Without
		// this, two editors could both read version 4, both write version 5,
		// and one change would vanish.
		const current = await client.query<{ version: string }>(
			`SELECT version FROM reports WHERE report_id = $1 FOR UPDATE`,
			[request.reportId],
		);
		const currentVersion = Number(current.rows[0]?.version ?? 0);

		if (currentVersion !== request.baseVersion) {
			throw new EditConflictError(
				"This report changed while you were editing it. Reload to see the current version.",
				currentVersion,
			);
		}

		// The client sends layout inside config because that is one object to
		// carry through the editor. It is split out here so the columns stay
		// the single source of position.
		const splitLayout = (
			config: Record<string, unknown> | undefined,
			explicit: VisualLayout | undefined,
		): { config: Record<string, unknown>; layout: VisualLayout | null } => {
			if (!config) return { config: {}, layout: explicit ?? null };
			const { layout, ...rest } = config as Record<string, unknown> & {
				layout?: VisualLayout;
			};
			return { config: rest, layout: explicit ?? layout ?? null };
		};

		for (const op of request.operations) {
			switch (op.type) {
				case "addVisual": {
					const next = await client.query<{ sort_order: number }>(
						`SELECT COALESCE(MAX(sort_order), -1) + 1 AS sort_order
						 FROM report_visuals WHERE page_id = $1`,
						[op.pageId],
					);
					const { config, layout } = splitLayout(op.config, op.layout);
					await client.query(
						`INSERT INTO report_visuals
						   (visual_id, page_id, visual_type, title, source_key, config,
						    layout_x, layout_y, layout_w, layout_h, sort_order)
						 VALUES (COALESCE($11::uuid, gen_random_uuid()),
						         $1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
						 ON CONFLICT (visual_id) DO NOTHING`,
						[
							op.pageId,
							op.visualType,
							op.title ?? null,
							op.sourceKey,
							JSON.stringify(config),
							layout?.x ?? 0,
							layout?.y ?? 0,
							layout?.w ?? 6,
							layout?.h ?? 4,
							next.rows[0]?.sort_order ?? 0,
							op.visualId ?? null,
						],
					);
					break;
				}

				case "updateVisual": {
					// Only the supplied fields change, so a client editing one
					// property does not have to send the whole visual back and
					// risk clobbering a property it never showed.
					const { config, layout } = splitLayout(op.config, op.layout);
					await client.query(
						`UPDATE report_visuals SET
						   title = COALESCE($2, title),
						   visual_type = COALESCE($3, visual_type),
						   source_key = COALESCE($4, source_key),
						   config = COALESCE($5::jsonb, config),
						   layout_x = COALESCE($6, layout_x),
						   layout_y = COALESCE($7, layout_y),
						   layout_w = COALESCE($8, layout_w),
						   layout_h = COALESCE($9, layout_h)
						 WHERE visual_id = $1`,
						[
							op.visualId,
							op.title ?? null,
							op.visualType ?? null,
							op.sourceKey ?? null,
							op.config ? JSON.stringify(config) : null,
							layout?.x ?? null,
							layout?.y ?? null,
							layout?.w ?? null,
							layout?.h ?? null,
						],
					);
					break;
				}

				case "removeVisual":
					// Deactivated rather than deleted, so a version restore can
					// bring it back and the audit trail still resolves it.
					await client.query(
						`UPDATE report_visuals SET is_active = FALSE WHERE visual_id = $1`,
						[op.visualId],
					);
					break;

				case "reorderVisuals":
					for (let i = 0; i < op.visualIds.length; i++) {
						await client.query(
							`UPDATE report_visuals SET sort_order = $2
							 WHERE visual_id = $1 AND page_id = $3`,
							[op.visualIds[i], i, op.pageId],
						);
					}
					break;

				case "updateReport":
					await client.query(
						`UPDATE reports SET
						   title = COALESCE($2, title),
						   description = COALESCE($3, description)
						 WHERE report_id = $1`,
						[request.reportId, op.title ?? null, op.description ?? null],
					);
					break;

				case "addPage": {
					const next = await client.query<{ sort_order: number }>(
						`SELECT COALESCE(MAX(sort_order), -1) + 1 AS sort_order
						 FROM report_pages WHERE report_id = $1`,
						[request.reportId],
					);
					await client.query(
						`INSERT INTO report_pages
						   (page_id, report_id, slug, title, source_key, sort_order)
						 VALUES ($1,$2,$3,$4,$5,$6)
						 ON CONFLICT (page_id) DO NOTHING`,
						[
							op.pageId,
							request.reportId,
							op.slug,
							op.title,
							op.sourceKey ?? null,
							next.rows[0]?.sort_order ?? 0,
						],
					);
					break;
				}

				case "removePage":
					// Deactivated rather than deleted, so a restore brings it
					// back and the visuals on it are not lost with it.
					await client.query(
						`UPDATE report_pages SET is_active = FALSE
						 WHERE page_id = $2 AND report_id = $1`,
						[request.reportId, op.pageId],
					);
					break;

				case "updatePage":
					await client.query(
						`UPDATE report_pages SET
						   title = COALESCE($3, title),
						   config = config || COALESCE($4::jsonb, '{}'::jsonb)
						 WHERE page_id = $2 AND report_id = $1`,
						[
							request.reportId,
							op.pageId,
							op.title ?? null,
							op.config ? JSON.stringify(op.config) : null,
						],
					);
					break;
			}
		}

		const nextVersion = currentVersion + 1;
		await client.query(
			`UPDATE reports
			 SET version = $2, modified_by = $3, modified_on = now()
			 WHERE report_id = $1`,
			[request.reportId, nextVersion, email],
		);

		// The op log is what other sessions replay. It is written inside the
		// same transaction as the change itself, so a session can never see an
		// op describing a change that did not land.
		const opRow = await client.query<{ seq: string }>(
			`INSERT INTO report_ops (report_id, actor, origin_id, op)
			 VALUES ($1, $2, $3, $4)
			 RETURNING seq`,
			[
				request.reportId,
				email,
				request.originId ?? null,
				JSON.stringify({
					version: nextVersion,
					operations: request.operations,
				}),
			],
		);
		const seq = Number(opRow.rows[0]?.seq ?? 0);

		// A snapshot per version, so any version can be restored and an edit
		// history reconstructed.
		//
		// Everything a restore has to put back, which means the layout columns
		// as well: without them a restore returned the right visuals with every
		// position lost, which is worse than not offering one.
		const snapshot = await client.query(
			`SELECT v.visual_id, v.page_id, v.visual_type, v.title, v.source_key,
			        v.config, v.layout_x, v.layout_y, v.layout_w, v.layout_h,
			        v.sort_order, v.is_active
			 FROM report_visuals v
			 JOIN report_pages p ON p.page_id = v.page_id
			 WHERE p.report_id = $1`,
			[request.reportId],
		);
		const pageSnapshot = await client.query(
			`SELECT page_id, slug, title, source_key, config, sort_order, is_active
			 FROM report_pages WHERE report_id = $1`,
			[request.reportId],
		);
		const reportSnapshot = await client.query(
			`SELECT title, description FROM reports WHERE report_id = $1`,
			[request.reportId],
		);

		await client.query(
			`INSERT INTO report_versions (report_id, version, snapshot, created_by)
			 VALUES ($1, $2, $3, $4)
			 ON CONFLICT (report_id, version) DO NOTHING`,
			[
				request.reportId,
				nextVersion,
				JSON.stringify({
					visuals: snapshot.rows,
					pages: pageSnapshot.rows,
					report: reportSnapshot.rows[0] ?? null,
				}),
				email,
			],
		);

		// Notification is a hint. Delivery is guaranteed by the sequence above,
		// so a listener that missed this still catches up on its next poll.
		await client.query(`SELECT pg_notify($1, $2)`, [
			`report_${request.reportId.replace(/-/g, "")}`,
			JSON.stringify({ seq, version: nextVersion, actor: email }),
		]);

		// Audit and telemetry go outside the transaction's critical path but
		// still describe what was committed.
		void insertLog({
			recordType: "report",
			recordId: request.reportId,
			action: "edit",
			changedBy: email,
			newValue: JSON.stringify({
				version: nextVersion,
				operations: request.operations.map((o) => o.type),
			}),
		});
		record({
			occurredOn: new Date().toISOString(),
			userEmail: email,
			policyClass: policy.id,
			eventType: "edit",
			reportId: request.reportId,
		});

		return { version: nextVersion, seq };
	});
}

export interface ReportOp {
	seq: number;
	actor: string;
	originId: string | null;
	op: { version: number; operations: EditOperation[] };
	createdOn: string;
}

// Everything that happened to a report after a given sequence. This is how a
// session catches up, whether it was notified or simply polled.
export async function opsSince(
	reportId: string,
	afterSeq: number,
	limit = 200,
): Promise<ReportOp[]> {
	const rows = await sql<{
		seq: string;
		actor: string;
		origin_id: string | null;
		op: ReportOp["op"];
		created_on: string;
	}>(
		`SELECT seq, actor, origin_id, op, created_on
		 FROM report_ops
		 WHERE report_id = $1 AND seq > $2
		 ORDER BY seq
		 LIMIT $3`,
		[reportId, afterSeq, limit],
	);

	return rows.map((row) => ({
		seq: Number(row.seq),
		actor: row.actor,
		originId: row.origin_id,
		op: row.op,
		createdOn: row.created_on,
	}));
}

// Trims the op log. Versions keep the full history, so ops only need to cover
// the window a disconnected session might have missed.
export async function pruneOps(olderThanHours = 48): Promise<number> {
	const rows = await sql<{ count: string }>(
		`WITH deleted AS (
		   DELETE FROM report_ops
		   WHERE created_on < now() - ($1 || ' hours')::interval
		   RETURNING 1
		 )
		 SELECT count(*)::text AS count FROM deleted`,
		[String(olderThanHours)],
	);
	return Number(rows[0]?.count ?? 0);
}
